---
- name: Desplegar aplicacion con Docker Compose
  hosts: gcp_servers
  become: yes
  tasks:
    - name: 1. Limpieza total de versiones previas
      file:
        path: /home/ubuntu/app
        state: absent

    - name: 2. Crear estructura de directorios limpia
      file:
        path: /home/ubuntu/app/html
        state: directory
        mode: '0755'

    - name: 3. Copiar archivos frescos desde el repositorio
      copy:
        src: app/  # Esto copiará el contenido de tu carpeta 'app' local
        dest: /home/ubuntu/app/
        force: yes

    - name: 4. Levantar contenedores con Docker Compose
      shell:
        cmd: /usr/bin/docker compose up -d --force-recreate
        chdir: /home/ubuntu/app/