---
- name: Desplegar aplicacion con Docker Compose
  hosts: gcp_servers
  become: yes
  tasks:
    - name: Crear directorio para la aplicacion
      file:
        path: /home/ubuntu/app/html
        state: directory
        mode: '0755'

    - name: Copiar archivos de la aplicacion
      copy:
        src: app/  # Quitamos el ./ para que sea relativo a la raíz del repo
        dest: /home/ubuntu/app/
        force: yes # <--- Obliga a sobreescribir si el archivo ya existe

    - name: Levantar contenedores con Docker Compose
      shell:
        cmd: /usr/bin/docker compose up -d --force-recreate
        chdir: /home/ubuntu/app/