name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          # Las comillas dobles son vitales para mantener los saltos de línea del formato PEM
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa_gcp
          chmod 600 ~/.ssh/id_rsa
          
          # Esto evita el error de "Host key verification failed"
          ssh-keyscan -H ${{ secrets.GCP_IP }} >> ~/.ssh/known_hosts

      - name: Run Ansible Playbook
        run: |
          # Usamos ubuntu, tu IP fija y el playbook que SI existe: deploy_all.yml
          ansible-playbook -i "${{ secrets.GCP_IP }}," deploy_all.yml \
            -u ubuntu \
            --private-key ~/.ssh/id_rsa_gcp \
            -e "ansible_python_interpreter=/usr/bin/python3"