name: Deploy to GCP

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Descargar codigo del repositorio
        uses: actions/checkout@v4

      - name: 2. Configurar llave SSH segura
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.GCP_IP }} >> ~/.ssh/known_hosts

      - name: 3. Instalar Ansible y Desplegar
        run: |
          pip install ansible
          # Creamos el inventario con el nombre de grupo [gcp_servers]
          echo "[gcp_servers]" > inventory_github.ini
          echo "${{ secrets.GCP_IP }} ansible_user=${{ secrets.GCP_USER }} ansible_ssh_private_key_file=~/.ssh/id_rsa ansible_ssh_common_args='-o StrictHostKeyChecking=no'" >> inventory_github.ini
          
          echo "Verificando inventario creado:"
          cat inventory_github.ini
          
          # Ejecutamos el despliegue
          ansible-playbook -i inventory_github.ini deploy_app.yml -v
          